apiVersion: apps/v1
kind: Deployment
metadata:
  name: radio
  labels:
    app: radio
spec:
  selector:
    matchLabels:
      app: radio
  replicas: 2   
  template:
    metadata:
      labels:
        app: radio
    spec:
      containers:
      - image: kyesikov/radio:latest
        name: radio
        ports:
        - containerPort: 3000
  
