apiVersion: apps/v1
kind: Deployment
metadata:
  name: radio
  labels:
    app: radio
spec:
  replicas: 2
  selector:
    matchLabels:
      app: radio
  template:
    metadata:
      labels:
        app: radio
    spec:
      containers:
      - image: kyesikov/radio:null
        name: radio
        ports:
        - containerPort: 3000
  replicas: 2
---
apiVersion: v1
kind: Service
metadata:
  name: radio-service
spec:
  selector:
    matchLabels:
      app: radio
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000
  type: LoadBalancer
