metadata:
  name: "radio"
  labels:
    app: "radio"
apiVersion: "apps/v1"
kind: "Deployment"
asset_id: "null-null"
spec:
  template:
    metadata:
      labels:
        app: "radio"
    spec:
      containers:
      - image: "kyesikov/radio:null"
        name: "radio"
        ports:
        - containerPort: 3000
  replicas: 2
  selector:
    matchLabels:
      app: "radio"
